### ISSUE TITLE
"Latest" Release?

### ISSUE THREAD

**Issue by Stickyhavr** [Stephen-Lon/Alfred-get-relative-date#1]
Hello again!
I noticed that 1.1 is released but version 1.01 is still showing at the "latest" release for this workflow.  I don't know much about GitHub but I'm hoping just bringing this to your attention is enough for you to figure out why it's doing that. :-)

Hope you're well. You can mark this as closed.

**Comment by Stephen-Lon** [comment]
Thanks for that. I've no idea why Github did that (very new user here!). It insisted to me that both releases were identical (they were not!) so in the end I deleted version 1.01 which leaves 1.1 as the latest. Thanks again for mentioning it.

Stephen
